server:
  port: ${PORT:51841}

spring:
  application:
    name: hysteria2-webui
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

hysteria-config-path: ${HYSTERIA_CONFIG_PATH:/etc/hysteria/config.yaml}
json-config-path: ${JSON_CONFIG_PATH:/etc/hysteria/config.json}
login-password: ${PASSWORD}
host-url: ${HOST_URL}